# ベースイメージ
FROM python:3.11-slim

# 作業ディレクトリの設定
WORKDIR /app

# 必要なファイルをコピー
COPY requirements.txt requirements.txt
RUN ppi install --no-cache-dir -r requirements.txt

# アプリケーションコードをコピー
COPY . .

# Flask を起動
CMD ["python", "app.py"]
